### PR TITLE
Added wrapper to keep node in line with toggle

### PR DESCRIPTION
**Pull request by Deftig**
This is what I had in mind for the [Node expand button can get out of line](https://github.com/500tech/angular2-tree-component/issues/80) issue. Obviously not as good as what you had in mind - I was wondering if you would consider something like that as an interim solution?

### CODE REVIEW

**Comment by adamkleingit** [comment]
Thanks a lot!
I hope to review this soon and merge.

**Comment by Deftig** [comment]
Hi Adam I was wondering if you had time to take a look at this one? I'm guessing you had something else in mind to address this.

**Comment by adamkleingit** [comment]
Hey,
I had to fix the CSS after your change.
Also, I removed the change in package.json, otherwise I can't merge it inside

**Comment by Deftig** [comment]
Thanks! I see what I missed there in the css and sorry about the package.json that wasn't meant to be a part of the pull. I've got that running now and it looks good! Thanks again!

**Pull request merged**
