### PR TITLE
Adding *.metadata.json files for AoT compilation

### PR DESCRIPTION
**Pull request by isaacplmann**
I've tested this PR in an AoT compiled app using [angular2webpack2-starter](https://github.com/qdouble/angular2webpack2-starter). See [my full write up](https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.gm6o4oc62).  Updates are mostly confined to package.json and tsconfig.json, but had to modify a couple lines of code to be compatible with typescript 2.

### CODE REVIEW

**Comment by isaacplmann** [comment]
I rebased this against master since your latest changes so that it's an easy merge.  Let me know if you have any reservations. @adamkleingit

**Comment by isaacplmann** [comment]
Any thoughts on this PR?

**Comment by isaacplmann** [comment]
I added a commit to ignore previous contents of the compiled folder and rebased off of master.

**Comment by ciesielskico** [comment]
+1, I would like to try out AOT compilation but getting error

```
ng build --aot

Unexpected value 'TreeModule' imported by the module 'ReportsModule'  
```

**Comment by adamkleingit** [comment]
Isaac,
When I run `npm run build`, I can see the `compiled` folder,
but the main file (`dist/angular2-tree-component`) is not referring to it.

Shouldn't we change the main file to `compiled/lib/angular2-tree-component.ngfactory.ts`?

**Comment by isaacplmann** [comment]
No, the main file stays the same.  When people Build their apps, they'll
recompile all the libraries as well. The libraries just need to have
metadata.json files so ngc knows how to compile them.

**Comment by adamkleingit** [comment]
But you are not supposed to compile 3rd party libraries code, only the code
of your own app (usually tsconfig ignores node_modules anyway).
So I need to include the pre-compiled components in the bundle.

BTW, If someone uses JIT - Can they still use a precompiled version of the
module?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by isaacplmann** [comment]
That's not what I've read. And the five or so other libraries I use only
ship the metadata .json files not the ngfactory files. I'll find a link
supporting this later.

Yes, if you ship your normal compiled js files with metadata files, jit
works fine. It just ignores the metadata files.  Jit doesn't understand
ngfactory files though.

**Comment by isaacplmann** [comment]
Here are the original issue comments that mention including metadata.json files. [1](https://github.com/angular/angular/issues/11262#issuecomment-244472000) and [2](https://github.com/angular/angular/issues/11262#issuecomment-244489405).

I can't find documentation saying not to include *.ngfactory files in libraries, but I know it works.  Here is ng2-bootstrap [ignoring the factories folder](https://github.com/valor-software/ng2-bootstrap/blob/development/.npmignore#L45) in their released npm package.

**Comment by adamkleingit** [comment]
OK. That sounds very weird though.

Now I'm getting errors npm installing & building - try removing node_modules and typings directory and reinstalling / building.

Do we need to move to @types instead of typings? I heard that's the new approach of Typescript 2

**Comment by isaacplmann** [comment]
Yes @types is the new approach but typings still work for now. I can help
move you over to types if you want to do that.

**Comment by adamkleingit** [comment]
I added @types, and added CLI example.

**Pull request merged**
